<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypened="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gearbox_interfaces</name>
  <version>0.0.1</version>
  <description>Custom ROS2 service, action, and message interfaces for gearbox disassembly.</description>
  <maintainer email="user@todo.todo">Zach Smith</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Message package dependencies -->
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <!-- Runtime dependencies -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Identifies this as an interface package -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>